<?php
/*
 * 接口基类
 *
 * */
namespace app\common\controller;


class ApiBase extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}