{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <div class="layui-btn-group">
            <a href="{:url('admin/user/add',['shop_id' => input('shop_id')])}" class="layui-btn ajax-iframe" data-width="390px" data-height="363px"><i class="fa fa-plus-circle"></i> 添加会员</a>
            <a href="{:url('admin/user/export')}" class="layui-btn layui-btn-primary"><i class="fa fa-file-excel-o"></i> 导出会员</a>
        </div>
        <table class="layui-table layui-form">
                <thead>
                        <tr>
                                <th>ID</th>
                                <th>商家</th>
                                <th>姓名</th>
                                <th>手机号</th>
                                <th>上次登录时间</th>
                                <th>上次登录IP</th>
                                <th>登录次数</th>
                                <th>创建时间</th>
                                <th>状态</th>
                                <th>操作</th>
                        </tr>
                </thead>
                <tbody>
                        {foreach name="list" item="v" empty="$empty"}
                        <tr>
                                <td>{$v.id}</td>
                                <td>{$v.shop_name}</td>
                                <td>{$v.name}</td>
                                <td>{$v.mobile}</td>
                                <td>{$v.last_login_time}</td>
                                <td>{$v.last_login_ip|default='无'}</td>
                                <td>{$v.login_count}</td>
                                <td>{$v.create_time}</td>
                                <td>
                                        <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="启用|禁用" data-url="{:url('admin/user/edit', ['id' => $v.id])}" {if $v.status eq 1}checked="checked"{/if}>
                                </td>
                                <td>
                                        <a href="{:url('admin/user/edit', ['id' => $v.id])}" data-width="390px" data-height="363px" class="layui-btn layui-btn-sm layui-btn-normal ajax-iframe"><i class="fa fa-edit"></i> 编辑</a>
                                        <a href="{:url('admin/user/del', ['id' => $v.id])}" class="layui-btn layui-btn-sm layui-btn-danger ajax-delete"><i class="fa fa-trash-o"></i> 删除</a>
                                </td>
                        </tr>
                        {/foreach}
                </tbody>
        </table>
        <div class="page">{$list|raw}</div>
    </div>
</div>
{/block}
