<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>HQadmin</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <link rel="stylesheet" href="/static/hqui/libs/layui/css/layui.css"/>
    <link rel="stylesheet" href="/static/hqui/module/admin.css?v=315"/>
  <link rel="stylesheet" href="/static/css/fonts.css">
  <link rel="stylesheet" href="/static/css/base.css">
  {block name="css"}{/block}
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        {block name="body"}{/block}
    </div>
</div>
<!--script src="/static/layui/layui.all.js"></script-->
<script src="/static/libs/layui/layui.all.js"></script>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/layui.base_mobile.js"></script>
<script src="/static/js/multiSelect.js"></script>
<script src="/static/js/common.js"></script>
{block name="js"}{/block}
</body>
</html>