{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <table class="layui-table layui-form">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>标题</th>
                    <th>点击量</th>
                    <th>添加时间</th>
                    <th>链接</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {foreach name="list" item="v" empty="$empty"}
                <tr>
                    <td>{$v.id}</td>
                    <td>{$v.title}</td>
                    <td>{$v.view}</td>
                    <td>{$v.datetime}</td>
                    <td><a href="{$v.url}" target="_blank" class="layui-btn layui-btn-xs layui-btn-radius" title="打开连接"><i class="fa fa-internet-explorer"></i></a></td>
                    <td>
                        <a href="{:url('admin/page/edit', ['id' => $v.id])}" class="layui-btn layui-btn-sm layui-btn-normal"><i class="fa fa-edit"></i> 编辑</a>
                    </td>
                </tr>
                {/foreach}
            </tbody>
        </table>
        <div class="page">{$list->render()}</div>
    </div>
</div>
{/block}