{extend name="base" /}
{block name="body"}
<div class="layui-card">
	<div class="layui-card-body">
        <div class="layui-btn-group">
		    <a href="{:url('admin/category/models_add')}" class="layui-btn ajax-iframe" data-width="400px" data-height="300px"><i class="fa fa-plus-circle"></i> 添加</a>
        </div>
		<table class="layui-table layui-form">
			<thead>
			<tr>
				<th>ID</th>
				<th>模型名称</th>
				<th>模型表</th>
                                <th>状态</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{foreach name="list" item="v" empty="$empty"}
			<tr>
				<td>{$v.id}</td>
				<td>{$v.name}</td>
                                <td>{$v.model}</td>
				<td>
                                    <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="启用|禁用" data-url="{:url('admin/category/models_edit', ['id' => $v.id])}" {if $v.status eq 1}checked="checked"{/if}>
				</td>
				<td>
                                    <a href="{:url('admin/category/models_edit', ['id' => $v.id])}" class="layui-btn layui-btn-sm layui-btn-normal ajax-iframe"  data-width="400px" data-height="300px"><i class="fa fa-edit"></i> 编辑</a>
                                    <a href="{:url('admin/category/models_del', ['id' => $v.id])}" class="layui-btn layui-btn-sm layui-btn-danger ajax-delete"><i class="fa fa-trash-o"></i> 删除</a>
				</td>
			</tr>
			{/foreach}
			</tbody>
		</table>
	</div>
</div>
{/block}
