<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" href="/favicon.ico" /> 
  <title>出纳宝</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <link rel="stylesheet" href="/static/layuiadmin/layui/css/layui.css" media="all">
  <link rel="stylesheet" href="/static/layuiadmin/style/admin.css" media="all">
  <link rel="stylesheet" href="/static/css/fonts.css">
</head>
<body class="layui-layout-body">
  <div id="LAY_app">
    <div class="layui-layout layui-layout-admin">
      <div class="layui-header">
        <!-- 头部区域 -->
        <ul class="layui-nav layui-layout-left">
          <li class="layui-nav-item layadmin-flexible" lay-unselect>
            <a href="javascript:;" layadmin-event="flexible" title="侧边伸缩">
              <i class="layui-icon layui-icon-shrink-right" id="LAY_app_flexible"></i>
            </a>
          </li>
          <li class="layui-nav-item" lay-unselect>
            <a href="javascript:;" layadmin-event="refresh" title="刷新">
              <i class="layui-icon layui-icon-refresh-3"></i>
            </a>
          </li>
          <li class="layui-nav-item layui-hide-xs" lay-unselect>
            <!--input type="text" placeholder="搜索客户..." autocomplete="off" class="layui-input layui-input-search" layadmin-event="serach" lay-action="/user/customer/index?cname="> 
          </li-->
        </ul>
        <ul class="layui-nav layui-layout-right" lay-filter="layadmin-layout-right">
            <li class="layui-nav-item" lay-unselect style="text-align: right;">
                <a target="_blank" href="http://doc.xianjinbiao.com" layadmin-event="message" lay-text="帮助文档">
                  <i class="layui-icon layui-icon-tips"></i>  帮助
                </a>
            </li>
            <!--li class="layui-nav-item" lay-unselect style="text-align: right;">
              <a lay-href="/user/remind/pending_today/" layadmin-event="message" lay-text="消息中心">
                <i class="layui-icon layui-icon-notice"></i>  提醒
                <!-- 如果有新消息，则显示小圆点 >
                <div id="count_remind">
                <span class="layui-badge" id="count_remind_num"></span>
                </div>
              </a>
            </li-->
            <li class="layui-nav-item" lay-unselect  style="margin-right:20px;text-align: right;">
              <a href="javascript:;">
                  <i class="layui-icon layui-icon-username"></i>
                  <cite>{if session('user_auth.realname')}{:session('user_auth.realname')}{else}{:session('user_auth.username')}{/if}</cite>
              </a>
              <dl class="layui-nav-child">
                <dd><a lay-href="{:url('user/index/editPassword')}">修改密码</a></dd>
                <hr>
                <dd style="text-align: center;"><a href="{:url('user/index/logout')}" >退出</a></dd>
              </dl>
            </li>


        </ul>
      </div>
        <!-- 侧边菜单 -->
        <div class="layui-side layui-side-menu">
          <div class="layui-side-scroll">
            <div class="layui-logo" lay-href="/user/index/home/">
                <span style="font-size:20px;">出纳宝</span>
            </div> 

            <ul class="layui-nav layui-nav-tree" lay-shrink="all" id="LAY-system-side-menu" lay-filter="layadmin-system-side-menu">
                <li data-name="home" class="layui-nav-item layui-nav-itemed">
                    <a href="javascript:;" lay-href="/user/index/home/" lay-tips="授权" lay-direction="2">
                      <i class="layui-icon layui-icon-home"></i>
                      <cite>系统首页</cite>
                    </a> 
                </li>
                <?php $i=1;?>
                {foreach name="navbar" item="v"}
                <li data-name="home" class="layui-nav-item {if $i=='1'}layui-nav-itemed{/if}">
                    <a {if condition="isset($v['children'])"}href="javascript:;"{else/}lay-href="{:url($v.url)}"{/if}>
                        <i class="layui-icon {$v.icon}"></i>
                        <cite>{$v.name}</cite>
                    </a>
                    {if condition="isset($v['children'])"}
                    <dl class="layui-nav-child">
                        {foreach name="v['children']" item="n1"}
                        <dd data-name="grid">
                            <a {if condition="isset($n1['children'])"}href="javascript:;"{else/}lay-href="{:url($n1.url)}"{/if}>{$n1.name}</a>
                            {if condition="isset($n1['children'])"}
                            <dl class="layui-nav-child">
                                {foreach name="n1['children']" item="n2"}
                                <dd data-name="list"><a lay-href="{:url($n2.url)}">{$n2.name}</a></dd>
                                {/foreach}
                            </dl>
                            {/if}
                        </dd>
                        {/foreach}
                    </dl>
                    {/if}
                </li>
                <?php $i++; ?>
                {/foreach}

            </ul>
          </div>
        </div>

      <!-- 页面标签 -->
      <div class="layadmin-pagetabs" id="LAY_app_tabs">
        <div class="layui-icon layadmin-tabs-control layui-icon-prev" layadmin-event="leftPage"></div>
        <div class="layui-icon layadmin-tabs-control layui-icon-next" layadmin-event="rightPage"></div>
        <div class="layui-icon layadmin-tabs-control layui-icon-down">
          <ul class="layui-nav layadmin-tabs-select" lay-filter="layadmin-pagetabs-nav">
            <li class="layui-nav-item" lay-unselect>
              <a href="javascript:;"></a>
              <dl class="layui-nav-child layui-anim-fadein">
                <dd layadmin-event="closeThisTabs"><a href="javascript:;">关闭当前标签页</a></dd>
                <dd layadmin-event="closeOtherTabs"><a href="javascript:;">关闭其它标签页</a></dd>
                <dd layadmin-event="closeAllTabs"><a href="javascript:;">关闭全部标签页</a></dd>
              </dl>
            </li>
          </ul>
        </div>
        <div class="layui-tab" lay-unauto lay-allowClose="true" lay-filter="layadmin-layout-tabs">
          <ul class="layui-tab-title" id="LAY_app_tabsheader">
            <li lay-id="/user/index/home" lay-attr="/user/index/home" class="layui-this"><i class="layui-icon layui-icon-home"></i> 系统首页</li>
          </ul>
        </div>
      </div>
      
      
      <!-- 主体内容 -->
      <div class="layui-body" id="LAY_app_body">
        <div class="layadmin-tabsbody-item layui-show">
          <iframe src="/user/index/home" frameborder="0" class="layadmin-iframe"></iframe>
        </div>
      </div>
      
      <!-- 辅助元素，一般用于移动设备下遮罩 -->
      <div class="layadmin-body-shade" layadmin-event="shade"></div>
    </div>
  </div>

<script src="/static/layuiadmin/layui/layui.js"></script>
<script src="/static/js/jquery.min.js"></script>
<script>
    layui.config({
      base: '/static/layuiadmin/' //静态资源所在路径
    }).extend({
      index: 'lib/index' //主入口模块
    }).use(['index'],function(){
        //var t = setInterval("get_remind()",60000);
        //if(t.count > '0'){
            
        //}
    });
    
    $(function () {
        $('.layui-nav-tree a').on('click', function () {
            var href = $(this).attr('lay-href');
            var li = $('li[lay-id="'+ href +'"]');
            if (li.length){
                li.find('.layui-tab-close').click();
            }
        })
    });
    //$("#count_remind").hide();
//    get_remind();
//    function get_remind(){
//        $.ajax({ 
//            type: 'POST',
//            url: "/user/index/get_count_remind/",
//            data:{},
//            success:function(data) {    
//                if (data.count=='0'){
//                    $("#count_remind").hide();
//                }else{
//                    $("#count_remind").show();
//                    $('#count_remind_num').html(data.count);
//                    layer.msg('今日您有 '+data.count+' 条信息待处理', {
//                            type: 1,
//                            offset:'rb',
//                            time: 10000, //不自动关闭
//                            yes: function(index){
//                                layer.close(index);
//                                //window.location.href='/user/remind/pending_today';
//                            }
//                        }
//                    );
//                };
//            },
//            dataType:'json',
//        });
//    }
    
</script>
</body>
</html>